name: shenai_sdk_minimal_example
description: Demonstrates how to use the shenai_sdk plugin.
version: 2.6.5

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shenai_sdk:
      # Specify a local relative path to the Shen.AI SDK
      path: ./shenai_sdk

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
