name: shenai_sdk_example
description: Demonstrates how to use the shenai_sdk plugin.
version: 1.0.2

publish_to: "none"

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  bloc: 8.1.0
  cupertino_icons: 1.0.5
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  flutter_native_splash: 2.2.8
  get_it: 7.2.0
  google_fonts: 3.0.1
  injectable: 1.5.3
  permission_handler: 10.0.0
  provider: 6.0.3
  rxdart: 0.27.5
  shenai_sdk:
    # Specify a local relative path to the Shen.AI SDK
    path: ./shenai_sdk

dev_dependencies:
  build_runner: 2.2.0
  flutter_launcher_icons: 0.10.0
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: 1.5.4
  integration_test:
    sdk: flutter
  lint: 1.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/dark/logo.png
    - assets/images/light/logo.png
    - assets/images/measure/
    - assets/images/measure/2.0x/
    - assets/images/measure/3.0x/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/light/logo.png
  image_dark: assets/images/dark/logo.png
  color_dark: "#042a49"
  android_12:
    color: "#ffffff"
    image: assets/images/light/logo.png
    image_dark: assets/images/dark/logo.png
    color_dark: "#042a49"
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#FF0000"
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
